/**
 * Application constants generated from the committed local mock snapshot.
 */

// Import the build-time configuration generated by scripts/generate-local-config.js.
import discoveredConfig from './discovered.json';

let DEFAULT_CLIENT_ID;
let DEFAULT_SUITE_ID;
let AVAILABLE_SUITES;

try {
  DEFAULT_CLIENT_ID = discoveredConfig.clientId;
  DEFAULT_SUITE_ID = discoveredConfig.currentSuite || discoveredConfig.suiteId; // Support both old and new structure
  AVAILABLE_SUITES = discoveredConfig.availableSuites || [DEFAULT_SUITE_ID]; // Support both old and new structure
  
  if (!DEFAULT_CLIENT_ID || !DEFAULT_SUITE_ID) {
    throw new Error('Missing required configuration in discovered.json');
  }
} catch (error) {
  throw new Error(`Failed to load generated local configuration: ${error.message}. Please run 'npm run prebuild'.`);
}

export { DEFAULT_CLIENT_ID, DEFAULT_SUITE_ID, AVAILABLE_SUITES };

// API Configuration (if needed in frontend)
export const API_CONFIG = {
  CLIENT_ID: DEFAULT_CLIENT_ID,
  SUITE_ID: DEFAULT_SUITE_ID,
  AVAILABLE_SUITES: AVAILABLE_SUITES
};
